experiment:
  algorithms:
    - expert_iteration_debug
      #- expert_iteration_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize
      #- expert_iteration_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize
      #- expert_iteration_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize
      ##
      #- expert_iteration_neural_net_opponent_modelling_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize
      #- expert_iteration_neural_net_opponent_modelling_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize
      #- expert_iteration_neural_net_opponent_modelling_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize
      ##
      #- expert_iteration_brexit_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize
      #- expert_iteration_brexit_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize
      #- expert_iteration_brexit_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize
  num_envs: 3
  environment:
    name: 'Connect4-v0' 
    env_type: 'multiagent-sequential'
  experiment_id: 'debug_BRExIt_Opponent_Modelling'
  desired_winrate: 1.1
  # ideally, a multiple of policy updates. Param :games_per iteration:
  training_episodes: 2
  benchmarking_episodes: 1


# --------- Agent hyperparameters ------
cnn_arch: &cnn_architecture
    phi_arch: 'CNN'
    use_batch_normalization: False
    preprocessed_input_dimensions: [7, 6]
    # Channels are: 3 (empty, p1 pieces, p2 pieces) * 4 stacked frames
    channels: [3, 15, 20, 20, 20, 1]
    kernel_sizes: [3, 3, 3, 3, 3]
    paddings: [1, 1, 1, 1, 1]
    strides: [1, 1, 1, 1, 1]
    residual_connections: [[0,1], [1,2], [2,3], [3,4]]
    final_feature_dim: 126

agents:
######## Vanilla ExIt ################
  expert_iteration: &vanilla_expert_iteration
    <<: *cnn_architecture
    use_agent_modelling: False
    use_true_agent_models_in_mcts: True
    use_apprentice_in_expert: True
    use_learnt_opponent_models_in_mcts: False
    use_cuda: False
    games_per_iteration: 500
    # Dataset params
    initial_memory_size: 30000
    increase_memory_every_n_generations: 2
    increase_memory_size_by: 10000
    end_memory_size: 120000
    # MCTS config
    mcts_budget: 50
    mcts_rollout_budget: 100
    mcts_exploration_factor: 4
    mcts_use_dirichlet: True
    # alpha > 1: flatten. alpha = 1: Uniform. alpha < 1, highlight random component
    mcts_dirichlet_alpha: 1.4142
    # Neural net config
    batch_size: 64
    num_epochs_per_iteration: 3
    learning_rate: 1.0e-3
    # NN: Feature extractor
    feature_extractor_arch: 'CNN'
    post_feature_extractor_arch: 'MLP'
    # We want to batch the stacked observations into different channels
    state_preprocessing_fn: 'turn_into_single_element_batch'
    server_state_preprocessing_fn: 'batch_vector_observation'

  expert_iteration_debug:
    <<: *vanilla_expert_iteration
    mcts_budget: 2
    mcts_rollout_budget: 0
    initial_memory_size: 10
    increase_memory_every_n_generations: 1
    increase_memory_size_by: 5
    end_memory_size: 30000
    use_apprentice_in_expert: True
    use_agent_modelling: True
    use_true_agent_models_in_mcts: True
    use_learnt_opponent_models: False
    use_dirichlet: False
    temperature: 1
    drop_temperature_after_n_moves: 2.
    games_per_iteration: 1
    batch_size: 2

  expert_iteration_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize:
    <<: *vanilla_expert_iteration
    mcts_budget: 20
    games_per_iteration: 500
    num_epochs_per_iteration: 3
    batch_size: 64

  expert_iteration_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize:
    <<: *vanilla_expert_iteration
    mcts_budget: 20
    games_per_iteration: 1000
    num_epochs_per_iteration: 5
    batch_size: 128

  expert_iteration_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize:
    <<: *vanilla_expert_iteration
    mcts_budget: 20
    games_per_iteration: 2000
    num_epochs_per_iteration: 8
    batch_size: 256

######## ExIt with opponent modelling on neural net (ala DPIQN) ################
  expert_iteration_neural_net_opponent_modelling_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: False
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 500
    num_epochs_per_iteration: 3
    batch_size: 64

  expert_iteration_neural_net_opponent_modelling_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: False
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 1000
    num_epochs_per_iteration: 5
    batch_size: 128

  expert_iteration_neural_net_opponent_modelling_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: False
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 2000
    num_epochs_per_iteration: 8
    batch_size: 256

######## ExIt with opponent modelling on neural net AND using true opponent models during search ################
  expert_iteration_brexit_500_GamesPerGeneration_20_MCTSBudget_NoRollout_3_epochs_64_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: True
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 500
    num_epochs_per_iteration: 3
    batch_size: 64

  expert_iteration_brexit_1000_GamesPerGeneration_20_MCTSBudget_NoRollout_5_epochs_128_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: True
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 1000
    num_epochs_per_iteration: 5
    batch_size: 128

  expert_iteration_brexit_2000_GamesPerGeneration_20_MCTSBudget_NoRollout_8_epochs_256_BatchSize:
    <<: *vanilla_expert_iteration
    use_agent_modelling: True
    use_true_agent_models_in_mcts: True
    use_apprentice_in_expert: True
    mcts_budget: 20
    games_per_iteration: 2000
    num_epochs_per_iteration: 8
    batch_size: 256
