algorithms:
- ppo
deltauniform:
  delta: 0.0
  save_after_policy_update: true
environment:
  env_type: multiagent-sequential
  name: Connect4-v0
experiment_id: fullhist_september_0
ppo:
  actor_arch: None
  adam_eps: 1.0e-05
  body_mlp_hidden_units:
  - 256
  - 128
  - 128
  channels:
  - 3
  - 32
  - 64
  - 64
  critic_arch: None
  discount: 0.99
  entropy_weight: 0.01
  final_feature_dim: 512
  gae_tau: 0.95
  gradient_clip: 1
  horizon: 8192
  kernel_sizes:
  - 3
  - 3
  - 3
  learning_rate: 0.0003
  mini_batch_size: 256
  optimization_epochs: 10
  paddings:
  - 1
  - 1
  - 1
  phi_arch: CNN-MLP
  ppo_ratio_clip: 0.2
  preprocessed_input_dimensions:
  - 7
  - 6
  residual_connections:
  - - 0
    - 1
  - - 2
    - 3
  state_preprocess_fn: turn_into_single_element_batch
  strides:
  - 1
  - 2
  - 1
  use_batch_normalization: false
  use_cuda: false
  use_gae: true
save_interval: 10000
self_play_training_schemes:
- deltauniform
training_episodes: 10000000
